
from pathlib import Path
import re
from typing import Optional

import pandas as pd


# Reading from specific formats
def read_deeplabcut_csv(file_path:str, file_name:str, nframes:Optional[int]=None):
    """ Load tracking data generated by DeepLabCut """

    # Extend file path
    file_path = Path(file_path) / file_name

    #  Get column names from second and third rows of dataframe
    cn = pd.read_csv(file_path, skiprows=1, nrows=1).iloc[0].to_dict()
    cn = {k:v for (k, v) in cn.items() if v != 'coords'}

    # Read in data (note that column names are split over two rows, which we need to correct)
    df = pd.read_csv(file_path, skiprows=2, nrows=nframes, index_col='coords')

    # Make column names useful
    new_names = {dfc: re.sub(r'\..','', k+v) for dfc, (k, v) in zip(df.columns, cn.items())}
    df.rename(columns=new_names, inplace=True)
    
    return df